FROM node:lts-alpine
LABEL authors="leandrocosta"

ENV PORT=8080
ENV DB_HOST='localhost'
ENV DB_PORT=5432
ENV DB_USERNAME='postgres'
ENV DB_PASSWORD='testpassword'
ENV DB_DATABASE='kudos-jaya'

ENV SLACK_CLIENT_ID=YOUR_SLACK_CLIENT_ID
ENV SLACK_CLIENT_SECRET=YOUR_SLACK_CLIENT_SECRET
ENV SLACK_SIGNING_SECRET=YOUR_SLACK_SIGNING_SECRET
ENV SLACK_APP_TOKEN=YOUR_SLACK_APP_TOKEN
ENV SLACK_BOT_TOKEN=YOUR_SLACK_BOT_TOKEN

WORKDIR /app

RUN chown -R node:node /app

COPY package.json /app

USER node

RUN npm install

COPY . /app

EXPOSE $PORT

CMD [ "npm", "start"]