FROM node:lts-alpine AS builder
LABEL authors="leandrocosta"

ENV PORT=PORT
ENV DB_HOST=DB_HOST
ENV DB_USER=DB_USER
ENV DB_PASSWORD=DB_PASSWORD
ENV DB_NAME=DB_NAME

ENV SLACK_CLIENT_ID=YOUR_SLACK_CLIENT_ID
ENV SLACK_CLIENT_SECRET=YOUR_SLACK_CLIENT_SECRET
ENV SLACK_SIGNING_SECRET=YOUR_SLACK_SIGNING_SECRET
ENV SLACK_APP_TOKEN=YOUR_SLACK_APP_TOKEN
ENV SLACK_BOT_TOKEN=YOUR_SLACK_BOT_TOKEN
ENV SLACK_STATE_SECRET=SLACK_STATE_SECRET
ENV TODO_BASE_URL=TODO_BASE_URL
ENV SLACK_LOGLEVEL=SLACK_LOGLEVEL
ENV SLACK_STATE_SECRET=SLACK_STATE_SECRET
ENV ENCRYPTION_KEY=ENCRYPTION_KEY
ENV GIPHY_API_KEY=GIPHY_API_KEY

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install
COPY . ./

# Compila o TypeScript para JavaScript
RUN npm run build

#Run stage
FROM node:lts-alpine AS runner
WORKDIR /app
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/config /app/config
RUN npm install --omit=dev
USER node
EXPOSE $PORT
CMD ["node", "dist/src/app.js"]
